# 开发环境配置
server:
  port: 2580
spring:
  profiles:
    active: devs
  freemarker:
    request-context-attribute: request  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/static/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  # H2数据库用来保存一些本地的数据
  datasource:
    url: jdbc:h2:./database
    driver-class-name: org.h2.Driver
    username: root
    password: root
  # 模板
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

  jpa:
    database: db2
    hibernate:
      ddl-auto: create-drop
  #配置能远程访问
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true


  mqtt:
    broker:

      # broker唯一标识,集群的时候使用
      id: mqtt-broker-1
      # SSL端口
      ssl-port: 8885
      # SSL密钥文件密码
      ssl-password: 123456
      # MQTT 端口
      mqtt-port: 1883
      # 认证方式
      # 1 clientID
      # 2 username && password
      auth-type: 1
      # SSL启用
      use-ssl: false
      #web控制台登陆口令
      web-console-token: qsedftr45g656hbtreQ#Q$RWDQ
      # websocket端口
      websocket-ssl-port: 9995
      # websocket path 值
      websocket-path: /web-socket-mqtt
      # 心跳时间(秒)
      keep-alive: 60
      # 开启Epoll模式, linux下建议开启
      use-epoll: false
      # 开启组播方式集群
      enable-multicast-group: true
      # 组播地址
      multicast-group: 239.255.255.255
      cache:
        # 持久化缓存内存初始化大小(MB)
        persistence-initial-size: 64
        # 持久化缓存占用内存最大值(MB)
        persistence-max-size: 128
        # 非持久化缓存内存初始化大小(MB)
        not-persistence-initial-size: 64
        # 非持久化缓存占用内存最大值(MB)
        not-persistence-max-size: 128
        # persistence-store-path: /mqtt-broker/persistence

# 日志 默认是debug
logging:
  level:
    root: info
    com.easyiot.iot.mqtt.server: info

# Spring监控
info:
  head: head
  body: body
management:
  endpoints:

    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false
    sessions:
      enabled:
